version: '2.3'
services:

  nginx:
    image: nginx:latest
    build:
      context: .
    container_name: nginx
    hostname: nginx
    mem_limit: 2048m
    restart: always
    ports: 
      - 8080:80

