version: '2.3'
services:

  jenkins:
    image: jenkins/jenkins:2.222.1
    container_name: jenkins
    mem_limit: 2048m
    restart: always
    ports:
      - '80:8080'
      - '443:443'
      - '50000:50000' #build executors port
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
