version: '2.3'

services:
  redis-cluster:
    image: grokzen/redis-cluster:latest
    container_name: redis-cluster
    hostname: redis-cluster
    mem_limit: 1024m
    restart: always
    volumes: 
      - ./redis-data:/redis-data
      - ./data:/data
    ports:
      - 5000:5000
      - 5001:5001
      # master
      - 7000:7000
      # master
      - 7001:7001
      # master
      - 7002:7002
      # slave
      - 7003:7003
      # slave
      - 7004:7004
      # slave
      - 7005:7005
    environment:
      IP: 0.0.0.0
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"