version: '2.3'                                                                                                                                                                                              
                                                  
services:   
  ubuntu:               
    image: ubuntucustom:$UBUNTU_VERSION
    build:
      context: .
      args:
        UBUNTU_VERSION: $UBUNTU_VERSION
    container_name: ubuntu
    hostname: ubuntu
    mem_limit: 2048m                           
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
