version: '2.3'

services:

  datascience-notebook:
    image: jupyter/datascience-notebook
    container_name: datascience-notebook
    hostname: datascience-notebook
    mem_limit: 2048m
    restart: always
    ports:
      - 8888:8888
    volumes:
      - ./storeddata/work:/home/jovyan/work
    user: root
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
    command: "start-notebook.sh --NotebookApp.password='sha1:1b05173510a1:64b02e937a1ef0d15930d8f0d3f1e94b04a1f8c7'" #Password1234!
