version: '2.3'                                                                                                                                                                                              
                                                  
services:   
  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: keycloak
    hostname: keycloak
    mem_limit: 2048m                             
    restart: always
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
    ports:
      - 8080:8080
    depends_on:
      - mysql
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

  mysql:
    image: mysql:5.7
    container_name: mysql
    hostname: mysql
    mem_limit: 2048m
    volumes:
      - ./mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"