version: '2.3'
services:
  influxdb:
    image: influxdb
    container_name: influxdb
    hostname: influxdb
    mem_limit: 2048m
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_DB=mysql_metrics
      - INFLUXDB_USER=admin
      - INFLUXDB_USER_PASSWORD=Password1234!
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=Password1234!
    volumes:
      - ./influxdb:/var/lib/influxdb
    networks:
      - grafana_network
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    healthcheck:
      test: "curl -f http://localhost:8086/ping"
      interval: 3s
      timeout: 10s
      retries: 5

  telegraf:
    image: telegraf
    container_name: telegraf
    hostname: telegraf
    mem_limit: 2048m
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - influxdb
    networks:
      - grafana_network
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    mem_limit: 2048m
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - grafana_network
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"

  grafana:
    image: grafana/grafana:6.1.4
    container_name: grafana
    hostname: grafana
    mem_limit: 2048m
    ports:
      - 3000:3000
    user: "104"
    environment:
      - GF_SERVER_ROOT_URL=https://grafana.example.com
      - GF_SECURITY_ADMIN_PASSWORD=Password1234!
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-worldmap-panel,raintank-worldping-app,jdbranham-diagram-panel,grafana-piechart-panel
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_DISABLE_GRAVATAR=true
      - GF_SERVER_DOMAIN=example.com
    volumes:
      - ./grafana:/var/lib/grafana
    networks:
      - grafana_network
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    healthcheck:
      test: ["CMD-SHELL", "curl -f localhost:3000/api/health && echo 'ready'"]
      interval: 10s
      retries: 30

networks:
  grafana_network:
    driver: bridge
