version: '2'
services:

  mariadb:
    image: bitnami/mariadb:10.1
    container_name: mariadb
    hostname: mariadb
    mem_limit: 2048m
    restart: always
    environment:
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./mariadb_data:/bitnami

  moodle:
    image: bitnami/moodle:3
    container_name: moodle
    hostname: moodle
    mem_limit: 2048m
    restart: always
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_USERNAME=user
      - MOODLE_PASSOWRD=bitnami
      - MOODLE_EMAIL=user@example.com
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./moodle_data:/bitnami
    depends_on:
      - mariadb
