version: '2.3'

services:

  mongodb:
    image: mongo
    container_name: mongodb
    hostname: mongodb
    mem_limit: 2048m
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db-data:/data/db
      # - ./mongo-config:/data/configdb
      # - ./mongo.conf:/etc/mongo.conf