version: '2.3'
services:
 jfrog-container-registry:
   image: docker.bintray.io/jfrog/artifactory-jcr:latest
   container_name: jfrog-container-registry
   mem_limit: 2048m
   restart: always
   ports:
    - 8081:8081
   # volumes:
   #  - ./data/artifactory:/var/opt/jfrog/artifactory