version: '2.3'

services:
  nginx: 
    image: nginx:latest
    container_name: nginx
    mem_limit: 1024m
    restart: always
    #volumes:
    #  - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443

