version: '2.3'

services:
  nexus3:
    image: sonatype/nexus3
    container_name: nexus3
    mem_limit: 2048m
    restart: always
    ports:
    - 8081:8081
    volumes:
    - ./data/artifactory:/var/opt/jfrog/artifactory
