version: '2.3'
services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:6.16.0
    container_name: artifactory-oss
    mem_limit: 2048m
    restart: always
    ports:
     - 80:8081
    volumes:
     - ./data/artifactory:/var/opt/jfrog/artifactory
#    Add extra Java options by uncommenting the following lines
#    environment:
#     - EXTRA_JAVA_OPTIONS=-Xmx2g
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000