version: '2'

services:
  mariadb:
    image: bitnami/mariadb:10.3
    container_name: mariadb
    environment:
      - MARIADB_USER=bn_testlink
      - MARIADB_DATABASE=bitnami_testlink
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mariadb_data:/bitnami

  testlink:
    image: bitnami/testlink
    container_name: testlink
    environment:
        # Use an existing database
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - TESTLINK_DATABASE_USER=bn_testlink
      - TESTLINK_DATABASE_NAME=bitnami_testlink
      - ALLOW_EMPTY_PASSWORD=yes
      # User and Site configuration
      - TESTLINK_USERNAME=administrator
      - TESTLINK_PASSWORD=Password1234!
      - TESTLINK_EMAIL=user@example.com
      - TESTLINK_LANGUAGE=en_US
    ports:
      - 80:80
      - 443:443
    volumes:
      - testlink_data:/bitnami
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
  testlink_data:
    driver: local
