version: '2.3'
services:

  charmuseum:
    image: chartmuseum/chartmuseum:v0.12.0
    mem_limit: 2048m
    restart: always
    ports:
      - '8080:8080'
    volumes:
      - ./charts:/charts
    environment:
      DEBUG: 1
      STORAGE: local
      STORAGE_LOCAL_ROOTDIR: /charts
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
